[project]
name = "pyjules"
version = "0.1.0"
description = "A convenient Python wrapper for running containerised JULES"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "udocker>=1.3.17",
]

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
]
